// Generated by CIRCT firtool-1.114.1
module ForwardingUnit(
  input  [4:0] io_rs1,
               io_rs2,
               io_exmemrd,
  input        io_exmemrw,
  input  [4:0] io_memwbrd,
  input        io_memwbrw,
  output [1:0] io_forwardA,
               io_forwardB
);

  assign io_forwardA =
    io_exmemrw & io_exmemrd == io_rs1 & (|io_exmemrd)
      ? 2'h1
      : {io_memwbrw & io_memwbrd == io_rs1 & (|io_memwbrd), 1'h0};
  assign io_forwardB =
    io_exmemrw & io_exmemrd == io_rs2 & (|io_exmemrd)
      ? 2'h1
      : {io_memwbrw & io_memwbrd == io_rs2 & (|io_memwbrd), 1'h0};
endmodule

