// Generated by CIRCT firtool-1.114.1
module HazardUnit(
  input  [4:0] io_rs1,
               io_rs2,
  input        io_idex_memread,
  input  [4:0] io_idex_rd,
  input        io_exmem_taken,
  output       io_pcfromtaken,
               io_pcstall,
               io_if_id_stall,
               io_id_ex_flush,
               io_ex_mem_flush,
               io_if_id_flush
);

  wire _GEN = io_idex_memread & (io_idex_rd == io_rs1 | io_idex_rd == io_rs2);
  wire io_pcstall_0 = ~io_exmem_taken & _GEN;
  assign io_pcfromtaken = io_exmem_taken;
  assign io_pcstall = io_pcstall_0;
  assign io_if_id_stall = io_pcstall_0;
  assign io_id_ex_flush = io_exmem_taken | _GEN;
  assign io_ex_mem_flush = io_exmem_taken;
  assign io_if_id_flush = io_exmem_taken;
endmodule

