// Generated by CIRCT firtool-1.114.1
module PipelinedCPU(
  input         clock,
                reset,
  output [63:0] io_imem_address,
  output        io_imem_valid,
  input         io_imem_good,
  input  [63:0] io_imem_instruction,
  input         io_imem_ready,
  output [63:0] io_dmem_address,
  output        io_dmem_valid,
  input         io_dmem_good,
  output [63:0] io_dmem_writedata,
  output        io_dmem_memread,
                io_dmem_memwrite,
  output [1:0]  io_dmem_maskmode,
  output        io_dmem_sext,
  input  [63:0] io_dmem_readdata
);

  wire [63:0] wb_writedata;
  wire        _mem_wb_ctrl_io_data_wb_ctrl_toreg;
  wire        _mem_wb_ctrl_io_data_wb_ctrl_regwrite;
  wire [63:0] _mem_wb_io_data_readdata;
  wire [63:0] _mem_wb_io_data_ex_result;
  wire [63:0] _mem_wb_io_data_instruction;
  wire [1:0]  _ex_mem_ctrl_io_data_mem_ctrl_memop;
  wire        _ex_mem_ctrl_io_data_wb_ctrl_toreg;
  wire        _ex_mem_ctrl_io_data_wb_ctrl_regwrite;
  wire [63:0] _ex_mem_io_data_ex_result;
  wire [63:0] _ex_mem_io_data_nextpc;
  wire        _ex_mem_io_data_taken;
  wire [63:0] _ex_mem_io_data_instruction;
  wire        _id_ex_ctrl_io_data_ex_ctrl_itype;
  wire        _id_ex_ctrl_io_data_ex_ctrl_aluop;
  wire        _id_ex_ctrl_io_data_ex_ctrl_src1;
  wire [1:0]  _id_ex_ctrl_io_data_ex_ctrl_src2;
  wire        _id_ex_ctrl_io_data_ex_ctrl_branch;
  wire [1:0]  _id_ex_ctrl_io_data_ex_ctrl_jumptype;
  wire        _id_ex_ctrl_io_data_ex_ctrl_resultselect;
  wire        _id_ex_ctrl_io_data_ex_ctrl_wordinst;
  wire [1:0]  _id_ex_ctrl_io_data_mem_ctrl_memop;
  wire        _id_ex_ctrl_io_data_wb_ctrl_toreg;
  wire        _id_ex_ctrl_io_data_wb_ctrl_regwrite;
  wire [63:0] _id_ex_io_data_pc;
  wire [63:0] _id_ex_io_data_instruction;
  wire [63:0] _id_ex_io_data_sextImm;
  wire [63:0] _id_ex_io_data_readdata1;
  wire [63:0] _id_ex_io_data_readdata2;
  wire [31:0] _if_id_io_data_instruction;
  wire [63:0] _if_id_io_data_pc;
  wire        _hazard_io_pcfromtaken;
  wire        _hazard_io_pcstall;
  wire        _hazard_io_if_id_stall;
  wire        _hazard_io_id_ex_flush;
  wire        _hazard_io_ex_mem_flush;
  wire        _hazard_io_if_id_flush;
  wire [1:0]  _forwarding_io_forwardA;
  wire [1:0]  _forwarding_io_forwardB;
  wire [63:0] _pcPlusFour_io_result;
  wire [63:0] _nextPCmod_io_nextpc;
  wire        _nextPCmod_io_taken;
  wire [63:0] _immGen_io_sextImm;
  wire [63:0] _alu_io_result;
  wire [4:0]  _aluControl_io_operation;
  wire [63:0] _registers_io_readdata1;
  wire [63:0] _registers_io_readdata2;
  wire        _control_io_itype;
  wire        _control_io_aluop;
  wire        _control_io_src1;
  wire [1:0]  _control_io_src2;
  wire        _control_io_branch;
  wire [1:0]  _control_io_jumptype;
  wire        _control_io_resultselect;
  wire [1:0]  _control_io_memop;
  wire        _control_io_toreg;
  wire        _control_io_regwrite;
  wire        _control_io_wordinst;
  reg  [63:0] pc;
  wire [63:0] _GEN = pc % 64'h8;
  wire [63:0] immGen_io_instruction = {32'h0, _if_id_io_data_instruction};
  reg  [63:0] casez_tmp;
  always_comb begin
    casez (_forwarding_io_forwardA)
      2'b00:
        casez_tmp = _id_ex_io_data_readdata1;
      2'b01:
        casez_tmp = _ex_mem_io_data_ex_result;
      2'b10:
        casez_tmp = wb_writedata;
      default:
        casez_tmp = 64'h0;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_0;
  always_comb begin
    casez (_forwarding_io_forwardB)
      2'b00:
        casez_tmp_0 = _id_ex_io_data_readdata2;
      2'b01:
        casez_tmp_0 = _ex_mem_io_data_ex_result;
      2'b10:
        casez_tmp_0 = wb_writedata;
      default:
        casez_tmp_0 = 64'h0;
    endcase
  end // always_comb
  assign wb_writedata =
    _mem_wb_ctrl_io_data_wb_ctrl_toreg
      ? _mem_wb_io_data_readdata
      : _mem_wb_io_data_ex_result;
  always @(posedge clock) begin
    if (reset)
      pc <= 64'h0;
    else if (_hazard_io_pcfromtaken)
      pc <= _ex_mem_io_data_nextpc;
    else if (_hazard_io_pcstall) begin
    end
    else
      pc <= _pcPlusFour_io_result;
  end // always @(posedge)
  Control control (
    .io_opcode       (_if_id_io_data_instruction[6:0]),
    .io_itype        (_control_io_itype),
    .io_aluop        (_control_io_aluop),
    .io_src1         (_control_io_src1),
    .io_src2         (_control_io_src2),
    .io_branch       (_control_io_branch),
    .io_jumptype     (_control_io_jumptype),
    .io_resultselect (_control_io_resultselect),
    .io_memop        (_control_io_memop),
    .io_toreg        (_control_io_toreg),
    .io_regwrite     (_control_io_regwrite),
    .io_wordinst     (_control_io_wordinst)
  );
  RegisterFile registers (
    .clock        (clock),
    .io_readreg1  (_if_id_io_data_instruction[19:15]),
    .io_readreg2  (_if_id_io_data_instruction[24:20]),
    .io_writereg  (_mem_wb_io_data_instruction[11:7]),
    .io_writedata (wb_writedata),
    .io_wen
      ((|(_mem_wb_io_data_instruction[11:7])) & _mem_wb_ctrl_io_data_wb_ctrl_regwrite),
    .io_readdata1 (_registers_io_readdata1),
    .io_readdata2 (_registers_io_readdata2)
  );
  ALUControl aluControl (
    .io_aluop     (_id_ex_ctrl_io_data_ex_ctrl_aluop),
    .io_itype     (_id_ex_ctrl_io_data_ex_ctrl_itype),
    .io_funct7    (_id_ex_io_data_instruction[31:25]),
    .io_funct3    (_id_ex_io_data_instruction[14:12]),
    .io_wordinst  (_id_ex_ctrl_io_data_ex_ctrl_wordinst),
    .io_operation (_aluControl_io_operation)
  );
  ALU alu (
    .io_operation (_aluControl_io_operation),
    .io_inputx    (_id_ex_ctrl_io_data_ex_ctrl_src1 ? _id_ex_io_data_pc : casez_tmp),
    .io_inputy
      (_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h0
         ? casez_tmp_0
         : _id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h1
             ? _id_ex_io_data_sextImm
             : {61'h0, _id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h2, 2'h0}),
    .io_result    (_alu_io_result)
  );
  ImmediateGenerator immGen (
    .io_instruction (immGen_io_instruction),
    .io_sextImm     (_immGen_io_sextImm)
  );
  NextPC nextPCmod (
    .io_branch   (_id_ex_ctrl_io_data_ex_ctrl_branch),
    .io_jumptype (_id_ex_ctrl_io_data_ex_ctrl_jumptype),
    .io_inputx   (casez_tmp),
    .io_inputy   (casez_tmp_0),
    .io_funct3   (_id_ex_io_data_instruction[14:12]),
    .io_pc       (_id_ex_io_data_pc),
    .io_imm      (_id_ex_io_data_sextImm),
    .io_nextpc   (_nextPCmod_io_nextpc),
    .io_taken    (_nextPCmod_io_taken)
  );
  Adder pcPlusFour (
    .io_inputx (pc),
    .io_result (_pcPlusFour_io_result)
  );
  ForwardingUnit forwarding (
    .io_rs1      (_id_ex_io_data_instruction[19:15]),
    .io_rs2      (_id_ex_io_data_instruction[24:20]),
    .io_exmemrd  (_ex_mem_io_data_instruction[11:7]),
    .io_exmemrw  (_ex_mem_ctrl_io_data_wb_ctrl_regwrite),
    .io_memwbrd  (_mem_wb_io_data_instruction[11:7]),
    .io_memwbrw  (_mem_wb_ctrl_io_data_wb_ctrl_regwrite),
    .io_forwardA (_forwarding_io_forwardA),
    .io_forwardB (_forwarding_io_forwardB)
  );
  HazardUnit hazard (
    .io_rs1          (_if_id_io_data_instruction[19:15]),
    .io_rs2          (_if_id_io_data_instruction[24:20]),
    .io_idex_memread (_id_ex_ctrl_io_data_mem_ctrl_memop == 2'h2),
    .io_idex_rd      (_id_ex_io_data_instruction[11:7]),
    .io_exmem_taken  (_ex_mem_io_data_taken),
    .io_pcfromtaken  (_hazard_io_pcfromtaken),
    .io_pcstall      (_hazard_io_pcstall),
    .io_if_id_stall  (_hazard_io_if_id_stall),
    .io_id_ex_flush  (_hazard_io_id_ex_flush),
    .io_ex_mem_flush (_hazard_io_ex_mem_flush),
    .io_if_id_flush  (_hazard_io_if_id_flush)
  );
  StageReg if_id (
    .clock               (clock),
    .reset               (reset),
    .io_in_instruction
      (_GEN[3:0] == 4'h4 ? io_imem_instruction[63:32] : io_imem_instruction[31:0]),
    .io_in_pc            (pc),
    .io_flush            (_hazard_io_if_id_flush),
    .io_valid            (~_hazard_io_if_id_stall),
    .io_data_instruction (_if_id_io_data_instruction),
    .io_data_pc          (_if_id_io_data_pc)
  );
  StageReg_1 id_ex (
    .clock               (clock),
    .reset               (reset),
    .io_in_pc            (_if_id_io_data_pc),
    .io_in_instruction   (immGen_io_instruction),
    .io_in_sextImm       (_immGen_io_sextImm),
    .io_in_readdata1     (_registers_io_readdata1),
    .io_in_readdata2     (_registers_io_readdata2),
    .io_flush            (_hazard_io_id_ex_flush),
    .io_data_pc          (_id_ex_io_data_pc),
    .io_data_instruction (_id_ex_io_data_instruction),
    .io_data_sextImm     (_id_ex_io_data_sextImm),
    .io_data_readdata1   (_id_ex_io_data_readdata1),
    .io_data_readdata2   (_id_ex_io_data_readdata2)
  );
  StageReg_2 id_ex_ctrl (
    .clock                        (clock),
    .reset                        (reset),
    .io_in_ex_ctrl_itype          (_control_io_itype),
    .io_in_ex_ctrl_aluop          (_control_io_aluop),
    .io_in_ex_ctrl_src1           (_control_io_src1),
    .io_in_ex_ctrl_src2           (_control_io_src2),
    .io_in_ex_ctrl_branch         (_control_io_branch),
    .io_in_ex_ctrl_jumptype       (_control_io_jumptype),
    .io_in_ex_ctrl_resultselect   (_control_io_resultselect),
    .io_in_ex_ctrl_wordinst       (_control_io_wordinst),
    .io_in_mem_ctrl_memop         (_control_io_memop),
    .io_in_wb_ctrl_toreg          (_control_io_toreg),
    .io_in_wb_ctrl_regwrite       (_control_io_regwrite),
    .io_flush                     (_hazard_io_id_ex_flush),
    .io_data_ex_ctrl_itype        (_id_ex_ctrl_io_data_ex_ctrl_itype),
    .io_data_ex_ctrl_aluop        (_id_ex_ctrl_io_data_ex_ctrl_aluop),
    .io_data_ex_ctrl_src1         (_id_ex_ctrl_io_data_ex_ctrl_src1),
    .io_data_ex_ctrl_src2         (_id_ex_ctrl_io_data_ex_ctrl_src2),
    .io_data_ex_ctrl_branch       (_id_ex_ctrl_io_data_ex_ctrl_branch),
    .io_data_ex_ctrl_jumptype     (_id_ex_ctrl_io_data_ex_ctrl_jumptype),
    .io_data_ex_ctrl_resultselect (_id_ex_ctrl_io_data_ex_ctrl_resultselect),
    .io_data_ex_ctrl_wordinst     (_id_ex_ctrl_io_data_ex_ctrl_wordinst),
    .io_data_mem_ctrl_memop       (_id_ex_ctrl_io_data_mem_ctrl_memop),
    .io_data_wb_ctrl_toreg        (_id_ex_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite     (_id_ex_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_3 ex_mem (
    .clock                 (clock),
    .reset                 (reset),
    .io_in_ex_result
      (_id_ex_ctrl_io_data_ex_ctrl_resultselect
         ? _id_ex_io_data_sextImm
         : _alu_io_result),
    .io_in_mem_writedata   (casez_tmp_0),
    .io_in_nextpc          (_nextPCmod_io_nextpc),
    .io_in_taken           (_nextPCmod_io_taken),
    .io_in_instruction     (_id_ex_io_data_instruction),
    .io_flush              (_hazard_io_ex_mem_flush),
    .io_data_ex_result     (_ex_mem_io_data_ex_result),
    .io_data_mem_writedata (io_dmem_writedata),
    .io_data_nextpc        (_ex_mem_io_data_nextpc),
    .io_data_taken         (_ex_mem_io_data_taken),
    .io_data_instruction   (_ex_mem_io_data_instruction)
  );
  StageReg_4 ex_mem_ctrl (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_mem_ctrl_memop     (_id_ex_ctrl_io_data_mem_ctrl_memop),
    .io_in_wb_ctrl_toreg      (_id_ex_ctrl_io_data_wb_ctrl_toreg),
    .io_in_wb_ctrl_regwrite   (_id_ex_ctrl_io_data_wb_ctrl_regwrite),
    .io_flush                 (_hazard_io_ex_mem_flush),
    .io_data_mem_ctrl_memop   (_ex_mem_ctrl_io_data_mem_ctrl_memop),
    .io_data_wb_ctrl_toreg    (_ex_mem_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite (_ex_mem_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_5 mem_wb (
    .clock               (clock),
    .reset               (reset),
    .io_in_readdata      (io_dmem_readdata),
    .io_in_ex_result     (_ex_mem_io_data_ex_result),
    .io_in_instruction   (_ex_mem_io_data_instruction),
    .io_data_readdata    (_mem_wb_io_data_readdata),
    .io_data_ex_result   (_mem_wb_io_data_ex_result),
    .io_data_instruction (_mem_wb_io_data_instruction)
  );
  StageReg_6 mem_wb_ctrl (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_wb_ctrl_toreg      (_ex_mem_ctrl_io_data_wb_ctrl_toreg),
    .io_in_wb_ctrl_regwrite   (_ex_mem_ctrl_io_data_wb_ctrl_regwrite),
    .io_data_wb_ctrl_toreg    (_mem_wb_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite (_mem_wb_ctrl_io_data_wb_ctrl_regwrite)
  );
  assign io_imem_address = pc;
  assign io_imem_valid = 1'h1;
  assign io_dmem_address = _ex_mem_io_data_ex_result;
  assign io_dmem_valid = _ex_mem_ctrl_io_data_mem_ctrl_memop[1];
  assign io_dmem_memread = ~(_ex_mem_ctrl_io_data_mem_ctrl_memop[0]);
  assign io_dmem_memwrite = _ex_mem_ctrl_io_data_mem_ctrl_memop[0];
  assign io_dmem_maskmode = _ex_mem_io_data_instruction[13:12];
  assign io_dmem_sext = ~(_ex_mem_io_data_instruction[14]);
endmodule

