// Generated by CIRCT firtool-1.114.1
module RegisterFile(
  input         clock,
  input  [4:0]  io_readreg1,
                io_readreg2,
                io_writereg,
  input  [63:0] io_writedata,
  input         io_wen,
  output [63:0] io_readdata1,
                io_readdata2
);

  reg [63:0] regs_0;
  reg [63:0] regs_1;
  reg [63:0] regs_2;
  reg [63:0] regs_3;
  reg [63:0] regs_4;
  reg [63:0] regs_5;
  reg [63:0] regs_6;
  reg [63:0] regs_7;
  reg [63:0] regs_8;
  reg [63:0] regs_9;
  reg [63:0] regs_10;
  reg [63:0] regs_11;
  reg [63:0] regs_12;
  reg [63:0] regs_13;
  reg [63:0] regs_14;
  reg [63:0] regs_15;
  reg [63:0] regs_16;
  reg [63:0] regs_17;
  reg [63:0] regs_18;
  reg [63:0] regs_19;
  reg [63:0] regs_20;
  reg [63:0] regs_21;
  reg [63:0] regs_22;
  reg [63:0] regs_23;
  reg [63:0] regs_24;
  reg [63:0] regs_25;
  reg [63:0] regs_26;
  reg [63:0] regs_27;
  reg [63:0] regs_28;
  reg [63:0] regs_29;
  reg [63:0] regs_30;
  reg [63:0] regs_31;
  reg [63:0] casez_tmp;
  always_comb begin
    casez (io_readreg1)
      5'b00000:
        casez_tmp = regs_0;
      5'b00001:
        casez_tmp = regs_1;
      5'b00010:
        casez_tmp = regs_2;
      5'b00011:
        casez_tmp = regs_3;
      5'b00100:
        casez_tmp = regs_4;
      5'b00101:
        casez_tmp = regs_5;
      5'b00110:
        casez_tmp = regs_6;
      5'b00111:
        casez_tmp = regs_7;
      5'b01000:
        casez_tmp = regs_8;
      5'b01001:
        casez_tmp = regs_9;
      5'b01010:
        casez_tmp = regs_10;
      5'b01011:
        casez_tmp = regs_11;
      5'b01100:
        casez_tmp = regs_12;
      5'b01101:
        casez_tmp = regs_13;
      5'b01110:
        casez_tmp = regs_14;
      5'b01111:
        casez_tmp = regs_15;
      5'b10000:
        casez_tmp = regs_16;
      5'b10001:
        casez_tmp = regs_17;
      5'b10010:
        casez_tmp = regs_18;
      5'b10011:
        casez_tmp = regs_19;
      5'b10100:
        casez_tmp = regs_20;
      5'b10101:
        casez_tmp = regs_21;
      5'b10110:
        casez_tmp = regs_22;
      5'b10111:
        casez_tmp = regs_23;
      5'b11000:
        casez_tmp = regs_24;
      5'b11001:
        casez_tmp = regs_25;
      5'b11010:
        casez_tmp = regs_26;
      5'b11011:
        casez_tmp = regs_27;
      5'b11100:
        casez_tmp = regs_28;
      5'b11101:
        casez_tmp = regs_29;
      5'b11110:
        casez_tmp = regs_30;
      default:
        casez_tmp = regs_31;
    endcase
  end // always_comb
  reg [63:0] casez_tmp_0;
  always_comb begin
    casez (io_readreg2)
      5'b00000:
        casez_tmp_0 = regs_0;
      5'b00001:
        casez_tmp_0 = regs_1;
      5'b00010:
        casez_tmp_0 = regs_2;
      5'b00011:
        casez_tmp_0 = regs_3;
      5'b00100:
        casez_tmp_0 = regs_4;
      5'b00101:
        casez_tmp_0 = regs_5;
      5'b00110:
        casez_tmp_0 = regs_6;
      5'b00111:
        casez_tmp_0 = regs_7;
      5'b01000:
        casez_tmp_0 = regs_8;
      5'b01001:
        casez_tmp_0 = regs_9;
      5'b01010:
        casez_tmp_0 = regs_10;
      5'b01011:
        casez_tmp_0 = regs_11;
      5'b01100:
        casez_tmp_0 = regs_12;
      5'b01101:
        casez_tmp_0 = regs_13;
      5'b01110:
        casez_tmp_0 = regs_14;
      5'b01111:
        casez_tmp_0 = regs_15;
      5'b10000:
        casez_tmp_0 = regs_16;
      5'b10001:
        casez_tmp_0 = regs_17;
      5'b10010:
        casez_tmp_0 = regs_18;
      5'b10011:
        casez_tmp_0 = regs_19;
      5'b10100:
        casez_tmp_0 = regs_20;
      5'b10101:
        casez_tmp_0 = regs_21;
      5'b10110:
        casez_tmp_0 = regs_22;
      5'b10111:
        casez_tmp_0 = regs_23;
      5'b11000:
        casez_tmp_0 = regs_24;
      5'b11001:
        casez_tmp_0 = regs_25;
      5'b11010:
        casez_tmp_0 = regs_26;
      5'b11011:
        casez_tmp_0 = regs_27;
      5'b11100:
        casez_tmp_0 = regs_28;
      5'b11101:
        casez_tmp_0 = regs_29;
      5'b11110:
        casez_tmp_0 = regs_30;
      default:
        casez_tmp_0 = regs_31;
    endcase
  end // always_comb
  always @(posedge clock) begin
    if (io_wen & io_writereg == 5'h0)
      regs_0 <= io_writedata;
    if (io_wen & io_writereg == 5'h1)
      regs_1 <= io_writedata;
    if (io_wen & io_writereg == 5'h2)
      regs_2 <= io_writedata;
    if (io_wen & io_writereg == 5'h3)
      regs_3 <= io_writedata;
    if (io_wen & io_writereg == 5'h4)
      regs_4 <= io_writedata;
    if (io_wen & io_writereg == 5'h5)
      regs_5 <= io_writedata;
    if (io_wen & io_writereg == 5'h6)
      regs_6 <= io_writedata;
    if (io_wen & io_writereg == 5'h7)
      regs_7 <= io_writedata;
    if (io_wen & io_writereg == 5'h8)
      regs_8 <= io_writedata;
    if (io_wen & io_writereg == 5'h9)
      regs_9 <= io_writedata;
    if (io_wen & io_writereg == 5'hA)
      regs_10 <= io_writedata;
    if (io_wen & io_writereg == 5'hB)
      regs_11 <= io_writedata;
    if (io_wen & io_writereg == 5'hC)
      regs_12 <= io_writedata;
    if (io_wen & io_writereg == 5'hD)
      regs_13 <= io_writedata;
    if (io_wen & io_writereg == 5'hE)
      regs_14 <= io_writedata;
    if (io_wen & io_writereg == 5'hF)
      regs_15 <= io_writedata;
    if (io_wen & io_writereg == 5'h10)
      regs_16 <= io_writedata;
    if (io_wen & io_writereg == 5'h11)
      regs_17 <= io_writedata;
    if (io_wen & io_writereg == 5'h12)
      regs_18 <= io_writedata;
    if (io_wen & io_writereg == 5'h13)
      regs_19 <= io_writedata;
    if (io_wen & io_writereg == 5'h14)
      regs_20 <= io_writedata;
    if (io_wen & io_writereg == 5'h15)
      regs_21 <= io_writedata;
    if (io_wen & io_writereg == 5'h16)
      regs_22 <= io_writedata;
    if (io_wen & io_writereg == 5'h17)
      regs_23 <= io_writedata;
    if (io_wen & io_writereg == 5'h18)
      regs_24 <= io_writedata;
    if (io_wen & io_writereg == 5'h19)
      regs_25 <= io_writedata;
    if (io_wen & io_writereg == 5'h1A)
      regs_26 <= io_writedata;
    if (io_wen & io_writereg == 5'h1B)
      regs_27 <= io_writedata;
    if (io_wen & io_writereg == 5'h1C)
      regs_28 <= io_writedata;
    if (io_wen & io_writereg == 5'h1D)
      regs_29 <= io_writedata;
    if (io_wen & io_writereg == 5'h1E)
      regs_30 <= io_writedata;
    if (io_wen & (&io_writereg))
      regs_31 <= io_writedata;
  end // always @(posedge)
  assign io_readdata1 = casez_tmp;
  assign io_readdata2 = casez_tmp_0;
endmodule

