Write-Host "Setting HAgent environment variables for PowerShell..."
$env:UV_PROJECT="D:\Github\hagent"
$env:HAGENT_ROOT="D:\Github\hagent"
$env:HAGENT_DOCKER="mascucsc/hagent-simplechisel:2025.09r"
$env:HAGENT_EXECUTION_MODE="docker"
$env:HAGENT_REPO_DIR="D:\Github\hagent\repo"
$env:HAGENT_BUILD_DIR="D:\Github\hagent\build"
$env:HAGENT_CACHE_DIR="D:\Github\hagent\cache"
$env:HAGENT_OUTPUT_DIR="D:\Github\hagent\logs"
Write-Host "Environment variables set. You can now run project commands."
