code_fix_generator:
  code_fix:
  - content: You are an expert programmer who specializes in fixing code bugs. Your
      task is to fix the provided code based on compiler error messages. Provide only
      the complete fixed code without explanations.
    role: system
  - content: 'Fix the following {language} code based on these compiler errors:


      Code:

      ```{language}

      {faulty_code}

      ```


      Errors:

      {compiler_errors}


      Provide the complete fixed code without explanations.'
    role: user
  llm:
    max_tokens: 2000
    model: openai/gpt-4-turbo-preview
    temperature: 0.2
