"""
Integration Test 2: Locate VCD Command

Tests the locator CLI functionality for mapping variables between HDL representations.
"""

import subprocess

import pytest


@pytest.mark.integration
@pytest.mark.cva6
def test_cva6_locate_vcd_mapping(cva6_setup, test_config):
    """
    Test locator CLI for mapping VCD signals to Verilog source in CVA6.

    Steps:
    1. Locate VCD files in repo or build directory
    2. Use cli_locator.py to map VCD signal to Verilog
    3. Validate mapping results
    """
    repo_dir = cva6_setup['repo_dir']
    build_dir = cva6_setup['build_dir']
    env = cva6_setup['env_vars']

    # Locate VCD files
    vcd_files = list(repo_dir.rglob('*.vcd')) + list(build_dir.rglob('*.vcd'))

    if not vcd_files:
        pytest.skip('No VCD files found for testing. VCD files may need to be generated by simulation.')

    vcd_file = vcd_files[0]
    print(f'Using VCD file: {vcd_file}')

    # Test variable mapping: VCD → Verilog
    # Try common signal names that might exist
    test_signals = ['top.clk_i', 'clk_i', 'clk', 'top.clk']

    success = False
    for signal in test_signals:
        locator_cmd = [
            'uv',
            'run',
            'python',
            '-m',
            'hagent.inou.cli_locator',
            '--api',
            'var',
            '--from',
            'vcd',
            '--to',
            'verilog',
            '--profile',
            'cva6_test',
            signal,
        ]

        result = subprocess.run(locator_cmd, env=env, capture_output=True, text=True)

        if result.returncode == 0:
            # Check that output contains some mapping information
            assert len(result.stdout) > 0, 'Locator returned empty output'
            print(f'Locator output for {signal}:\\n{result.stdout}')
            success = True
            break

    if not success:
        pytest.skip(f'Could not find mappable signal in VCD. Tried: {test_signals}')


@pytest.mark.integration
@pytest.mark.simplechisel
def test_simplechisel_locate_vcd_mapping(simplechisel_setup, test_config):
    """
    Test locator CLI for mapping VCD signals to Verilog source in SimpleChisel.

    Similar to CVA6 test but for SimpleChisel.
    """
    repo_dir = simplechisel_setup['repo_dir']
    build_dir = simplechisel_setup['build_dir']
    env = simplechisel_setup['env_vars']

    # Locate VCD files
    vcd_files = list(repo_dir.rglob('*.vcd')) + list(build_dir.rglob('*.vcd'))

    if not vcd_files:
        pytest.skip('No VCD files found for testing.')

    vcd_file = vcd_files[0]
    print(f'Using VCD file: {vcd_file}')

    # Test with common SimpleChisel signal names
    test_signals = ['top.clock', 'clock', 'top.reset', 'reset', 'io_x', 'io_y']

    success = False
    for signal in test_signals:
        locator_cmd = [
            'uv',
            'run',
            'python',
            '-m',
            'hagent.inou.cli_locator',
            '--api',
            'var',
            '--from',
            'vcd',
            '--to',
            'verilog',
            '--profile',
            'simplechisel_test',
            signal,
        ]

        result = subprocess.run(locator_cmd, env=env, capture_output=True, text=True)

        if result.returncode == 0:
            assert len(result.stdout) > 0
            print(f'Locator output for {signal}:\\n{result.stdout}')
            success = True
            break

    if not success:
        pytest.skip(f'Could not find mappable signal in VCD. Tried: {test_signals}')
