// Generated by CIRCT firtool-1.62.0
module Counter(        // src/main/scala/Counter.scala:6:7
  input        clock,   // src/main/scala/Counter.scala:6:7
               reset,   // src/main/scala/Counter.scala:6:7
               io_enable,       // src/main/scala/Counter.scala:7:14
               io_reset,        // src/main/scala/Counter.scala:7:14
  output [3:0] io_count // src/main/scala/Counter.scala:7:14
);

  reg [3:0] countReg;   // src/main/scala/Counter.scala:14:25
  always @(posedge clock) begin // src/main/scala/Counter.scala:6:7
    if (reset)  // src/main/scala/Counter.scala:6:7
      countReg <= 4'h0; // src/main/scala/Counter.scala:14:25
    else if (io_reset)  // src/main/scala/Counter.scala:7:14
      countReg <= 4'h0; // src/main/scala/Counter.scala:14:25
    else if (io_enable) // src/main/scala/Counter.scala:7:14
      countReg <= countReg - 4'h1;      // src/main/scala/Counter.scala:14:25, :19:26
  end // always @(posedge)
  assign io_count = countReg;   // src/main/scala/Counter.scala:6:7, :14:25
endmodule

