#!/bin/bash
#
# Setup script for SimpleChisel MCP server
# Creates the necessary directory structure and configuration files
# for running the HAgent MCP server with SimpleChisel

# Set default values
HAGENT_ROOT=${HAGENT_ROOT:-$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)}
HAGENT_DOCKER=${HAGENT_DOCKER:-"mascucsc/hagent-simplechisel:2025.08"}

# Use current directory as base directory unless specified
BASE_DIR=${1:-$(pwd)}

# Create directories
mkdir -p "${BASE_DIR}/repo" "${BASE_DIR}/build" "${BASE_DIR}/cache" "${BASE_DIR}/cache/mcp"

# Path to the MCP server
MCP_SERVER_PATH="${HAGENT_ROOT}/hagent/mcp/hagent-mcp-server.py"

# Create the hagent_server.sh script
cat >"${BASE_DIR}/hagent_server.sh" <<EOF
#!/bin/bash
#
# HAgent MCP Server launcher
# Generated by setup_simplechisel_mcp.sh
#
# Usage: ./hagent_server.sh [--debug]
# Use --debug for detailed logging and raw I/O transaction logs in cache/mcp/

export UV_PROJECT="${HAGENT_ROOT}"
export HAGENT_ROOT="${HAGENT_ROOT}"
export HAGENT_DOCKER="${HAGENT_DOCKER}"
export HAGENT_EXECUTION_MODE="docker"
export HAGENT_REPO_DIR="${BASE_DIR}/repo"
export HAGENT_BUILD_DIR="${BASE_DIR}/build"
export HAGENT_CACHE_DIR="${BASE_DIR}/cache"
export HAGENT_OUTPUT_DIR="${BASE_DIR}/logs"

# Pass through any command line arguments (like --debug)
uv run python ${MCP_SERVER_PATH} "\$@"
EOF

# Make the script executable
chmod +x "${BASE_DIR}/hagent_server.sh"

# Create Claude MCP config file
cat >"${BASE_DIR}/hagent_mcp_conf.json" <<EOF
{
  "mcpServers": {
    "hagent": {
      "command": "uv",
      "args": ["run", "python", "${MCP_SERVER_PATH}"],
      "env": {
        "UV_PROJECT": "${HAGENT_ROOT}",
        "HAGENT_ROOT": "${HAGENT_ROOT}",
        "HAGENT_DOCKER": "${HAGENT_DOCKER}",
        "HAGENT_EXECUTION_MODE": "docker",
        "HAGENT_REPO_DIR": "${BASE_DIR}/repo",
        "HAGENT_BUILD_DIR": "${BASE_DIR}/build",
        "HAGENT_CACHE_DIR": "${BASE_DIR}/cache"
      }
    }
  }
}
EOF

echo
echo "Setup complete!"
echo
echo "Directory structure created:"
echo "- ${BASE_DIR}/repo  (for source code)"
echo "- ${BASE_DIR}/build (for build outputs)"
echo "- ${BASE_DIR}/cache (for cached files)"
echo "- ${BASE_DIR}/cache/mcp (for MCP transaction logs)"
echo
echo "Generated files:"
echo "- ${BASE_DIR}/hagent_server.sh (executable server launcher)"
echo "- ${BASE_DIR}/hagent_mcp_conf.json (Claude MCP configuration)"
echo
echo "To use with Gemini:"
echo "  gemini add hagent ${BASE_DIR}/hagent_server.sh"
echo
echo "To use with Claude:"
echo "  claude --mcp-config ${BASE_DIR}/hagent_mcp_conf.json"
echo
echo "For permanent Claude setup:"
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "  cp ${BASE_DIR}/hagent_mcp_conf.json ~/Library/Application\\ Support/Claude/claude_desktop_config.json"
else
  echo "  cp ${BASE_DIR}/hagent_mcp_conf.json ~/.config/claude/claude_desktop_config.json"
fi
echo

