#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HAGENT_ROOT=${HAGENT_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}

ESP_IDF_VERSION="v5.2.1"
ESP_IDF_REPO="https://github.com/espressif/esp-idf.git"

SOURCE_C_FILE="${HAGENT_ROOT}/examples/esp32_led/blink.c"


# Use current directory as base directory unless specified as an argument
BASE_DIR=${1:-$(pwd)}
BASE_DIR_ABS=$(cd "${BASE_DIR}" && pwd)

echo "--- ESP32 MCP Setup ---"
echo "Project Location: ${BASE_DIR_ABS}"
echo "HAGENT Root:      ${HAGENT_ROOT}"
echo "-----------------------"

# 1. Create project directories
echo
echo "[1/5] Creating project directories..."
mkdir -p "${BASE_DIR_ABS}/repo"
mkdir -p "${BASE_DIR_ABS}/build"
mkdir -p "${BASE_DIR_ABS}/cache"
mkdir -p "${BASE_DIR_ABS}/logs"
echo "Done."

# 2. Install ESP-IDF
ESP_IDF_PATH="${BASE_DIR_ABS}/cache/esp-idf"
echo
echo "[2/5] Setting up ESP-IDF..."
if [ ! -d "${ESP_IDF_PATH}" ]; then
  echo "Cloning ESP-IDF version ${ESP_IDF_VERSION}..."
  if command -v git >/dev/null 2>&1; then
    git clone --depth 1 --branch ${ESP_IDF_VERSION} ${ESP_IDF_REPO} "${ESP_IDF_PATH}"
  else
    echo "Error: git is not installed. Cannot clone ESP-IDF." >&2
    exit 1
  fi
else
  echo "ESP-IDF already found at ${ESP_IDF_PATH}."
fi

if [ -f "${ESP_IDF_PATH}/install.sh" ]; then
  echo "Installing ESP-IDF tools..."
  "${ESP_IDF_PATH}/install.sh" esp32c3
else
  echo "Error: ESP-IDF install script not found." >&2
  exit 1
fi
echo "Done."

# 3. Create project
REPO_PATH="${BASE_DIR_ABS}/repo"
PROJECT_CREATED=false # Flag to track if we created the project
echo
echo "[3/5] Creating ESP32 project..."

# Check if the repo directory is NOT empty
if [ -n "$(ls -A "${REPO_PATH}")" ]; then
    echo "Repo directory is not empty. Skipping project creation."
else
    PROJECT_CREATED=true
    echo "Sourcing ESP-IDF environment..."
    source "${ESP_IDF_PATH}/export.sh"

    echo "Creating project with command: (cd '${REPO_PATH}' && idf.py create-project -p . blink_project)"
    (cd "${REPO_PATH}" && idf.py create-project -p . blink_project)

    PROJECT_PATH="${REPO_PATH}"
    echo "Setting target to esp32c3..."
    idf.py -C "${PROJECT_PATH}" set-target esp32c3
fi
echo "Done."

# 4. Copy custom C file
echo
echo "[4/5] Copying custom main file..."
if [ "$PROJECT_CREATED" = true ]; then
    if [ -f "${SOURCE_C_FILE}" ]; then
      cp "${SOURCE_C_FILE}" "${PROJECT_PATH}/main/blink_project.c"
      echo "Replaced default main file with content from ${SOURCE_C_FILE}."
    else
      echo "Warning: Source file ${SOURCE_C_FILE} not found." >&2
    fi
else
    echo "Skipping file copy because project creation was skipped."
fi


# 5. Create the hagent_server.sh script
MCP_SERVER_PATH="${HAGENT_ROOT}/hagent/mcp/hagent-mcp-server.py"
HAGENT_SERVER_SCRIPT_PATH="${BASE_DIR_ABS}/hagent_server.sh"
echo
echo "[5/5] Generating hagent_server.sh launcher..."

cat >"${HAGENT_SERVER_SCRIPT_PATH}" <<EOF
#!/bin/bash
#
# HAgent MCP Server launcher for local ESP32 development
# Generated by setup_esp32_mcp.sh
#
# Usage: ./hagent_server.sh [--debug]
#

# Set environment variables for HAgent
export UV_PROJECT="${HAGENT_ROOT}"
export HAGENT_ROOT="${HAGENT_ROOT}"
export HAGENT_EXECUTION_MODE="local"
export HAGENT_REPO_DIR="${BASE_DIR_ABS}/repo"
export HAGENT_BUILD_DIR="${BASE_DIR_ABS}/build"
export HAGENT_CACHE_DIR="${BASE_DIR_ABS}/cache"
export HAGENT_OUTPUT_DIR="${BASE_DIR_ABS}/logs"

# Source the ESP-IDF environment to make idf.py and other tools available
source "${ESP_IDF_PATH}/export.sh"

# Pass through any command line arguments (like --debug) to the MCP server
# uv run python ${MCP_SERVER_PATH} "\$@"
EOF

# Make the script executable
chmod +x "${HAGENT_SERVER_SCRIPT_PATH}"
echo "Done."

echo
echo "--- Setup Complete! ---"
echo
echo "A new ESP32 project has been created at: ${PROJECT_PATH}"
echo "The project is configured for the ESP32-C3."
echo
echo "To use with Gemini:"
echo "  gemini add hagent ${HAGENT_SERVER_SCRIPT_PATH}"
echo
echo "To run the server manually:"
echo "  ${HAGENT_SERVER_SCRIPT_PATH}"
echo
